# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PDE7jkpuOfXXFujrSLkpcF0N1i0ZYmZ8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from google.colab import files
import io

uploaded = files.upload()
dataset = pd.read_csv(io.BytesIO(uploaded['day.csv']))
dataset.head()

dataset.info()

dataset.describe()

sb.pairplot(dataset)

sb.heatmap(dataset.corr())

dataset.corr()

X=dataset[['instant','season','yr','mnth','holiday','weekday','workingday','weathersit','temp','atemp','hum','windspeed','casual','registered']]
Y=dataset['cnt']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=100)

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,Y_train)

df_coef=pd.DataFrame(lr.coef_,X.columns,columns=['Coefficient'])
print(df_coef)
