# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJgQS8RzGcFg3EnlTnBw-ngwS8zBo8au
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline

BikeSharing = pd.read_csv("/day.csv")
BikeSharing.head()

BikeSharing.info()

BikeSharing.describe()

sns.pairplot(BikeSharing)

BikeSharing.columns

sns.distplot(BikeSharing['cnt'])

sns.heatmap(BikeSharing.corr())

BikeSharing.corr()

X = BikeSharing[['instant', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered']]
Y = BikeSharing['cnt']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.4, random_state=101)

from sklearn.linear_model import LinearRegression

lm = LinearRegression()
lm.fit(X_train,y_train)

print(lm.intercept_)

coeff_df = pd.DataFrame(lm.coef_,X.columns,columns=['Coefficient'])
coeff_df

predictions = lm.predict(X_test)

plt.scatter(y_test,predictions)