#Created by abhishek kamble---------
# -*- coding: utf-8 -*-
"""SETL2_2019BTECS00068_2019BTECS00073.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TULQLx2d-DGdVpPN_mNYWKDT_T0wZjwc
"""

from google.colab import drive
drive.mount("/content/drive/")

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Dataset = pd.read_csv("/content/drive/MyDrive/hungary_chickenpox.csv")

# importing an array of features
x = Dataset.iloc[:, :-1].values 
# importing an array of dependent variable
y = Dataset.iloc[:, -1].values

print(x) # returns an array of features

print(y) # viewing an array of the dependent variable.

from sklearn.impute import SimpleImputer
# To replace the missing value we create below object of SimpleImputer class
imputa = SimpleImputer(missing_values = np.nan, strategy = 'mean')
''' Using the fit method, we apply the `imputa` object on the matrix of our feature x.
The `fit()` method identifies the missing values and computes the mean of such feature a missing value is present.
'''
imputa.fit(x[:, 1:3])
# Repalcing the missing value using transform method
x[:, 1:3] = imputa.transform(x[:, 1:3])

print(x)

# Encoding categorial data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder= 'passthrough')
x = np.array(ct.fit_transform(x))

print(x)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

# importing an array of features
x = Dataset.iloc[:, :-1].values 
# importing an array of dependent variable
y = Dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.4,random_state= 1)

print(x_train)

print(x_test)

print(y_train)

print(y_test)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
# we only aply the feature scaling on the features other than dummy variables.
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

print(x_train)

print(x_test)

Dataset2 = pd.read_csv("/content/drive/MyDrive/hungary_county_edges.csv")

# importing an array of features
x = Dataset2.iloc[:, :-1].values 
# importing an array of dependent variable
y = Dataset2.iloc[:, -1].values

print(x) # returns an array of features

print(y) # viewing an array of the dependent variable.